---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-hd

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: recyclarr-hd-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RADARR_API_KEY: "{{ .RADARR__API_KEY }}"
        SONARR_API_KEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr-hd
        property: RADARR__API_KEY
    - extract:
        key: sonarr-hd
        property: SONARR__API_KEY
