---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-hd

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-hd-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        RADARR__API_KEY: "{{ .RADARR__API_KEY }}"
        RADARR__POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        RADARR__POSTGRES_PORT: "5432"
        RADARR__POSTGRES_USER: &dbUser "{{ .RADARR__POSTGRES_USER }}"
        RADARR__POSTGRES_PASSWORD: &dbPass "{{ .RADARR__POSTGRES_PASSWORD }}"
        RADARR__POSTGRES_MAIN_DB: radarr_hd_main
        RADARR__POSTGRES_LOG_DB: radarr_hd_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: radarr_hd_main radarr_hd_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: radarr-hd
    - extract:
        key: cloudnative-pg
