---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-hd-config

spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-filesystem
