---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugin-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  values:
    resources:
      requests:
        cpu: 5m
        memory: 100Mi
      limits:
        memory: 500Mi
