---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adguardhome-sync

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: adguardhome-sync-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ORIGIN_PASSWORD: "{{ .ORIGIN_PASSWORD }}"
        REPLICA_PASSWORD: "{{ .REPLICA_PASSWORD }}"
        API_PASSWORD: "{{ .API_PASSWORD }}"
  dataFrom:
    - extract:
        key: adguardhome-sync
