---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: adguard-sync
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: adguardhome-sync-settings
        containers:
          main:
            image:
              repository: ghcr.io/bakito/adguardhome-sync
              tag: v0.5.4@sha256:94fe42977704ad19faddf0136e8a6a0cf4b5848216139b110012f02da2b3bbfd
            envFrom:
              - secretRef:
                  name: adguardhome-sync-secret
            nodeSelector:
              amd.feature.node.kubernetes.io/gpu: true
    service:
      main:
        ports:
          http:
            port: 8080
    persistence:
      config:
        enabled: true
        type: configMap
        name: adguardhome-sync-configmap
        subPath: adguardhome-sync.yaml
        mountPath: /config/adguardhome-sync.yaml
        readOnly: false
