# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-secret
    namespace: kube-system
stringData:
    token: ENC[AES256_GCM,data:YJJ+o33VfUZAI8+c7TkhIosK6j29AcAakq848s5bcSzajjzh+BVwoe6U7eDM9diaERCEHUpz0hSg7huAr9S5sFiHvywlls1ghEQ3grLitKEHzZK6d4BYtDvMxV832SsVyTKtmUhcuiAuZJ4IIM31Fk63hhECNS55IR9FcpDBpxEbqBklaayy3CAYE/fh2DAxVtfdJGAY79REGbA4h8e9tE2bwErAelEPVsTugwq2j+K78H59II57IosHi2+VvOWoBJ6Y4FYb/zmzRtdM+JIA7VXsHO+vIF5Hr3Nozh1CNK0W/PIilh7udQXJLBBMwVSHMgSi6a3m90lKO3343eEPFHhZzIockvBIEw7S5MfTkDpFB2xtAwA67pHmOaf/uuz+v3BZyTpuK6f7ezW2kTTcVG8/YWXpeqxtm8jCm0qlVHij6IQVgMxt9rT1i9V0eWpJgCKjLejVH9Z10QPdo7R2XLWNc7NgufFs1cdCd49HKzAdGJ6SA+PUIM6BbBDTpGhUs9jdZQUC1xTTGGgUAU2kKuOY7D0TbmtsH7mz+AoQfxKTVxfiuE38bLjvRXEQiobqgy1DzrgcuBkIJkzW1BqHDjWVm9rh8muH1HvkwPoSAEeco1a/+Yyl1CPecM+N08v2VhHkxcQei3EBEMIe6c7VsRRAgtwW8aQfHA5XcAgOl/jGNrxR2tx97PsVsGcsWbX1O255GTo+BnLOFvX/VCl5BN8GEUq04vzu3U6UOVOTgPAEDACgM+GS5BGFb/Tv3wMXO08rVQV4l59C8V5fK87jdnZhFlhFSVCrfOZTf74ktvUCS717Wa0Sty7kUGoJnXsIzG+1FZxp+R19Y3AS3lPLtxwr,iv:rYRXlJ+b2mXkPO7UH6d30W0kg+4AtEXjZsrbJs0Fnhg=,tag:laFUA5goo6lQP/A0A80XnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdFVVZzhmWnQrNVVzd1hD
            SFVRcGhpNzljeTlkQU53UVp3dVFCUGNZbXpFClZqMmZmMFJwSzN2cFl5NjFjTmRO
            bGQvYTJ6WkN4akU2RVN1c00rMUlabW8KLS0tIDJGeSt3NWloSFNrMFRKSTdFQXJ5
            UG9iemkxc2k1MU5uQno3cTN1NVdVZWsK/KdYLMpHWWYYGmhMZZT6hBhW/RFdwQdo
            vFqypXH9CqvZs4iSyjmyV0PQeFAYVvx9iBO5NUOEwMbWStybYgESbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-08T12:36:35Z"
    mac: ENC[AES256_GCM,data:uhUe3No2b6telCaJmgU06DsKeFAYAHRw7wC1amsrXYq69r9D/+ELMlKC2PbadWBmN5WeQ4r57Mm0sWwzUE7iBfP6zhcL3wLalyDt44H/V7aiguBncBKBkIV8TCJu3jE1uVhq3wPzi6SdbDv7WRFJ6t0XW9LDGK4yUHkwWeSIPVU=,iv:T0Vu56Z0NcB0YjqZoq6AXVy2hEfKDPKl1HJJJN0EEt4=,tag:CS4ygSiYbPUJW8NfUb8Oxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
