ansible_become_pass: ENC[AES256_GCM,data:wciJwjLxpd2d/jeo,iv:KV8kFphf5MdXMaH9QbTULAkSSSNK000So+6tmwvUIL0=,tag:OR2WI2ZAf7mN1SvU3S3dug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbEhIbVNxb1ZRRExuMHh2
            eTZHZGtjc1FPd2JLL0hsb0g4V3JxSTlUZ1dvCjVQTCt5WUhXUFJKZ2ZZSTFvNlkz
            N2UzL3gzbHpUdXdIZHpudFFUcVBxUVEKLS0tIGVBUVZ4SGIwaWVLVUx4VEIrOEtk
            OWFRa1RCWWtkejVJeXhvSllDQ2dQaWcKLPfgDy/faplI5J7vYdWHC/h1SM9Yz43+
            KQO7GM40QGG4Y/8SgjidoDNTon4xdWIjdI+omb/r+kcfVzdq+wCLvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T22:20:24Z"
    mac: ENC[AES256_GCM,data:s8zzczt9/z7fiymMGImbr0XoC8flXiudVywihIPV/CdfeAFIAmAxrJCjjp9fPztgc4muTHxd6yAifjyC0lcCsOEyqWiNTAZQDSsP9A4TIJhuPECYYT/R+EniEpDBw+ivnlfQCfKS0QGHq/tVLC4JijBLPRl2zSF3NuqdFTb8+BI=,iv:kSn3IThLWQLt+fTZlyFcDup3HMPKfCVdJbSRzvxnx8s=,tag:2KVPXXfHT6hMt4TMP7t66Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
