---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: amd-gpu-helm
  namespace: flux-system
spec:
  interval: 2h
  url: https://radeonopencompute.github.io/k8s-device-plugin/
