---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: amd-dp-gpu-device
spec:
  rules:
    - name: "amd.gpu"
      labels:
        "amd.feature.node.kubernetes.io/gpu": "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: [ "1002" ] }
            class: { op: In, value: [ "0300" ] }
        - feature: kernel.loadedmodule
          matchExpressions:
            amdgpu: { op: Exists }
