---
# yaml-language-server: $schema=https://kubernetes-schemas.prymal.info/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugin-gpu
spec:
  interval: 15m
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: intel-device-plugin-operator
      namespace: kube-system
  values:
    name: intel-device-plugin-gpu
    sharedDevNum: 3
    nodeFeatureRule: false
