---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./media-pvc.yaml
  - ./adguard-sync/ks.yaml
  - ./discord-template-notifier/ks.yaml
  - ./hajimari/ks.yaml
  - ./overseerr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./kubernetes-schemas/ks.yaml
