---
# yaml-language-server: $schema=http://kubernetes-schemas.prymal.info/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: amd-gpu-node-labeller
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: amd-device-plugin
      namespace: kube-system
  values:
    defaultPodOptions:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
      nodeSelector:
        feature.node.kubernetes.io/pci-0300_1002.present: "true"
        kubernetes.io/arch: amd64
      priorityClassName: system-node-critical
    controllers:
      main:
        type: daemonset
        containers:
          main:
            image:
              repository: docker.io/rocm/k8s-device-plugin
              tag: labeller-1.25.2.5
            workingDir: /root
            command: ["/root/k8s-node-labeller"]
            args:
              [
                "-logtostderr=true",
                "-stderrthreshold=INFO",
                "-v=5",
                "-vram",
                "-cu-count",
                "-simd-count",
                "-device-id",
                "-family",
              ]
            env:
              TZ: America/Denver
              DS_NODE_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
            resources:
              requests:
                cpu: 25m
                memory: 10Mi
              limits:
                memory: 100Mi
            securityContext:
              privileged: true
              capabilities:
                drop: ["ALL"]
    serviceAccount:
      create: false
      name: amd-gpu-node-labeller
    service:
      main:
        enabled: false
    persistence:
      sys:
        enabled: true
        type: hostPath
        hostPath: /sys
      dev:
        enabled: true
        type: hostPath
        hostPath: /dev
