apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:1lbG8eD/HbEqli+pmJPB2O3iusw=,iv:NbSQqog7DIT5otg1/4SNIIRTeu1m1+1gecGQOn3WeiQ=,tag:JWFUldwyTWRWuMAKmvIiLg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:SKfZwIXlaYk2Wsu5ACe5V4xvDGTlMIuCMHEo5D/QKgeGjJ2o,iv:QR5W85opL6LqFdwzzaUOpuy5Rok7GbiPm9fMLa7uMn8=,tag:5gp1bpIbLvPtUyYfvjQaOw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:kj+HveBaHOY9+IQ=,iv:hfrKsWjJ+hRHnm/jXvQS7FiPvCx+4kVpNxD5bM2oa/I=,tag:/KXeWil+71XOqS+EGwE0kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsR2kyZysxVDVydzJGcnd2
            dUY0aGYvNFh6T1Z4WlRXSm41S216NWhxZFZNClBTbXpleTQyUkZPbGEwSEppN0FN
            MWpUd0tVdmJuVkltQXpkRTR1MHgxNUkKLS0tIFRrQzI5cy9lNmIwcjN3VERxbE93
            YmhjbllVUnNsUng2SW1PbmdmZHp5a2MK2xP1hDxMIxlGp0dcZzYkDrEeFaOxlExy
            nUpTJe8JmAhf1SK3cxQfrq8BGKCdd/F1SN54TIM0iWG+oTkUi9HgUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T22:21:23Z"
    mac: ENC[AES256_GCM,data:faGfVclAYuxkWsnEV3fFj+wHg+SEEpxCSLl3jak0npljPEdSLU8t0/SNYHQgsIzJGhBRIorAQySeP3dq7oZsjEFSdvR28zLMhOp/yoBxBA2ImmS5h26T8s0teKiyMHH7uw3xSnnoqelSNJIYDh6SQa2nzK4s89FE1UYM/76iwrY=,iv:jJR9LhEaHo2lmgrGrf8BPV5sQQejdnRve3a88A/bE9w=,tag:kg4lAHXqjas2zSj7//PfVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
