apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:SL8lohwfYGJ7KV9i,iv:W6UoaZjueItFbd9We9YQOwiHwUKnb0gKpK6O9MCQH60=,tag:meccmpPIj02yJUDV/L8XOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTnZ5dzM2SlF3R25RSW56
            RWhYOUhFTzhlWER5U3FvWFAzTzk5bGRKK0RvCi9HZ0kwN09Qem91R0IxMXY2REFm
            TlQwL3QrTktEZ2p6VjFZSUFwd0dqenMKLS0tIDBjN01FUWhVSVhSeDRwYVI0VXhY
            RFhmYStMdVZCQlZPa2QzRWFvV1FBNncKt3fXVYzAjgiQNv5F+rjhHcs58J9pS3f1
            FkNe8yGxWosNOPDF6dLpvGh3MUtAk7D2CrQewG4jkPBp4j9FzBU2MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T21:49:58Z"
    mac: ENC[AES256_GCM,data:aCg4SZZbEtDE8sLEkBd5/309GacAv8IkBiQCvq/zK/Y9jU0ludSHRL1TmiC7yxHBysXmNbm2UFCkfFrh5CnVI4U45BM1MoOYQxrwXoMhZQNVPRFBv5AWoNsplUc29K5JiAPKexs0wM+/v1bTy4FUqL/TEW9ySnMVl8LC8OXGIKI=,iv:xaWWIDPj4Wiv1EbwYgJHKzyhFsUi2KoWXq0ZmFaV6Ng=,tag:c5RKwawv5M7T8+kcNYW5ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
