apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:8drwWw7gGZTIQDcLHXPRuggYvnOPc02q,iv:JCja2GCM/0piF64Fxtk3rVCKYkcCoCvzQz/WHykW3DE=,tag:7//z7KtVPUrGFIl2YkWpYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zvdg9nspexxpnt6c2h8mprq0y86jn4agz933z524egwumkr2rcmq806a2s
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV3BkSzVQTW14TVN4UDMz
            QkZDUUd1VjlJMHZ0VGRmOFhFeUlyZklUQXhrCnhaY25CaDQ1bFRPZkNsMWw3WWp6
            bTA3NVFSQlJUR25sM0ZMNTA0TWpIOFUKLS0tIGxJSTJ3N3o1dHY0ZFJ6MHVWRnNy
            NThIM0lmTm5SYnowNFhGSjFRQjBFd2cK63BydPQNAMMR+aZjYdQ5/hYL+nxVIqTW
            vsrzLoh2/YKkq949BigDGxBFh7uYjycq3f2FwRrdbq7MIgYbsi08ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-25T22:21:21Z"
    mac: ENC[AES256_GCM,data:cQnE/kk6fh7rqB1VslDP321204qu9TLuzBsXNpJKUTJvwdz72pnj2FbMd0sRVXsE+h6jwziycmQfiNGMLsAFwWlLkz+o9QoLQ7CJlb7AFDobnVGfEENV2QG9f76vl62aqPqW/OSAJOZQfU5ZKZLXOW/8y5HywO4QQ9dT6XVMd5k=,iv:uTohlq3rBvhfVTx8KFYY5xEZTngaHAJn8G6TKfNitxg=,tag:Qd1Rem4zt2xc2X6e47t2wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
